application: sens3-histogram
version: 1
runtime: go
api_version: go1

handlers:    
- url: /css
  static_dir: public/css
  
- url: /js
  static_dir: public/js  

- url: /images
  static_dir: public/images  
  
- url: /.*
  script: _go_app