application: sens3go
version: 1
runtime: go
api_version: go1

handlers:    
- url: /css
  static_dir: public/css
  
- url: /js
  static_dir: public/js  

- url: /html
  static_dir: public/html
  
- url: /.*
  script: _go_app